create database PINNACLEDB;

create schema ECART;

create table ECART.CUSTOMER (
	CUSTID VARCHAR(50),
	CUSTNAME VARCHAR(100),
	CUSTADD VARCHAR(400)
);

create table ECART.PRODUCTINFO (
	PRODUCTID INTEGER,
	PRODUCTNAME VARCHAR(150),
	PRODCAT VARCHAR(400),
	STOREID VARCHAR(70),
	PRODUCTPRICE FLOAT
);

create table ECART.STOREINFO (
	STOREID VARCHAR(70),
	STORENAME VARCHAR(150),
	STOREADD VARCHAR(400)
);

create table ECART.FACT_ORDER (
	ORDERID SERIAL PRIMARY key,
	CUSTID VARCHAR(50),
	PRODUCTID INTEGER,
	PURCHASETIMESTAMP TIMESTAMP with TIME ZONE default CURRENT_TIMESTAMP
);

select * from ECART.FACT_ORDER;
select * from ECART.STOREINFO;
select * from ECART.PRODUCTINFO;
select * from ECART.CUSTOMER;

select count(*) from ECART.FACT_ORDER;
select count(*) from ECART.STOREINFO;
select count(*) from ECART.PRODUCTINFO;
select count(*) from ECART.CUSTOMER;